version: "3.5"
services:
  db:
    build:
      context: ./db_schema
    image: "koala/lada_db"
    volumes:
      - ./db_schema:/opt/lada_sql/
  server:
    build:
      context: ./
    image: "koala/lada_wildfly"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/lada-server
    ports:
      - 8080 # direct access to interfaces
      - 9990 # Wildfly management console
      - 8787 # Remote debugging of server code
      - 5005 # Remote debugging of test code
  client:
    image: "koala/lada_client"
    depends_on:
      - server
    volumes:
      - ../client:/usr/local/lada # Assumes client checkout in ../client
    ports:
      - 80-86
