version: "3.5"
services:
  db:
    container_name: "lada_db"
    build:
      context: ./db_schema
    image: "koala/lada_db"
    networks:
      - lada_network
    volumes:
      - ./db_schema:/opt/lada_sql/
  server:
    container_name: "lada-server"
    build:
      context: ./
    image: "koala/lada_wildfly"
    networks:
      - lada_network
    depends_on:
      - db
    volumes:
      - ./:/usr/src/lada-server
    ports:
      - 8080:8080 # direct access to interfaces
      - 9990:9990 # Wildfly management console
      - 8787:8787 # Remote debugging of server code
      - 5005:5005 # Remote debugging of test code
  printer:
    container_name: "lada-printer"
    image: "koala/gis_print_templates"
    networks:
      - lada_network
    volumes:
      # Assumes checkout in ../gis_print_templates/:
      - ../gis_print_templates/:/usr/local/tomcat/webapps/bfs-printservice/print-apps
  client:
    container_name: "lada-client"
    image: "koala/lada_client"
    networks:
      - lada_network
    depends_on:
      - server
      - printer
    volumes:
      - ../client:/usr/local/lada # Assumes client checkout in ../client
    ports:
      - 8180-8186:80-86
networks:
  lada_network:
    name: lada_network
