#!/bin/bash
set -Eeo pipefail

LADA_DB_SRV=${LADA_DB_SRV:-db}
LADA_DB_NAME=${LADA_DB_NAME:-lada}
LADA_DB_USER=${LADA_DB_USER:-lada}
LADA_DB_PW=${LADA_DB_PW:-lada}
LADA_DB_PORT=${LADA_DB_PORT:-5432}
LADA_JBOSS_HOME=${LADA_JBOSS_HOME:-/opt/jboss/wildfly}
LADA_JBOSS_ADMIN=${LADA_JBOSS_ADMIN:-ADMIN}
LADA_JBOSS_PW=${LADA_JBOSS_PW:-secret}

export WILDFLY_OVERRIDING_ENV_VARS=1

export SUBSYSTEM_DATASOURCES_DATA_SOURCE_LADA__CONNECTION_URL=jdbc:postgresql://${LADA_DB_SRV}:${LADA_DB_PORT}/${LADA_DB_NAME}
export SUBSYSTEM_DATASOURCES_DATA_SOURCE_LADA__USER_NAME=${LADA_DB_USER}
export SUBSYSTEM_DATASOURCES_DATA_SOURCE_LADA__PASSWORD=${LADA_DB_PW}

export JAVA_OPTS='${LADA_JAVA_OPTS}'
/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
